/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.30
 * Generated at: 2025-01-02 16:34:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user.cart;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Gio hang</title>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"span12\">\r\n");
      out.write("			<ul class=\"breadcrumb\">\r\n");
      out.write("				<li><a href=\"index.html\">Home</a> <span class=\"divider\">/</span></li>\r\n");
      out.write("				<li class=\"active\">Check Out</li>\r\n");
      out.write("			</ul>\r\n");
      out.write("			<div class=\"well well-small\">\r\n");
      out.write("				<h1>\r\n");
      out.write("					Check Out <small class=\"pull-right\"> 2 Items are in the\r\n");
      out.write("						cart </small>\r\n");
      out.write("				</h1>\r\n");
      out.write("				<hr class=\"soften\" />\r\n");
      out.write("\r\n");
      out.write("				<table class=\"table table-bordered table-condensed\">\r\n");
      out.write("					<thead>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<th>Product</th>\r\n");
      out.write("							<th>Description</th>\r\n");
      out.write("							<th>Ref.</th>\r\n");
      out.write("							<th>Color</th>\r\n");
      out.write("							<th>Avail.</th>\r\n");
      out.write("							<th>Unit price</th>\r\n");
      out.write("							<th>Qty</th>\r\n");
      out.write("							<th>Total</th>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</thead>\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><img width=\"100\" src=\"assets/img/e.jpg\" alt=\"\"></td>\r\n");
      out.write("							<td>Items name here<br>Carate : 22<br>Model : n/a\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>-</td>\r\n");
      out.write("\r\n");
      out.write("							<td><span class=\"shopBtn\"><span class=\"icon-ok\"></span></span>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>$50.00</td>\r\n");
      out.write("							<td><input class=\"span1\" style=\"max-width: 34px\"\r\n");
      out.write("								placeholder=\"1\" id=\"appendedInputButtons\" size=\"16\" type=\"text\"\r\n");
      out.write("								value=\"2\">\r\n");
      out.write("								<div class=\"input-append\">\r\n");
      out.write("									<button class=\"btn btn-mini\" type=\"button\">-</button>\r\n");
      out.write("									<button class=\"btn btn-mini\" type=\"button\">+</button>\r\n");
      out.write("									<button class=\"btn btn-mini btn-danger\" type=\"button\">\r\n");
      out.write("										<span class=\"icon-remove\"></span>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div></td>\r\n");
      out.write("							<td>$100.00</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td><img width=\"100\" src=\"assets/img/f.jpg\" alt=\"\"></td>\r\n");
      out.write("							<td>Item names and brief details<br>Carate:24 <br>Model:HBK24\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>-</td>\r\n");
      out.write("							<td><span class=\"shopBtn\"><span class=\"icon-ok\"></span></span>\r\n");
      out.write("							</td>\r\n");
      out.write("							<td>$348.42</td>\r\n");
      out.write("							<td><input class=\"span1\" style=\"max-width: 34px\"\r\n");
      out.write("								placeholder=\"1\" size=\"16\" type=\"text\">\r\n");
      out.write("								<div class=\"input-append\">\r\n");
      out.write("									<button class=\"btn btn-mini\" type=\"button\">-</button>\r\n");
      out.write("									<button class=\"btn btn-mini\" type=\"button\">+</button>\r\n");
      out.write("									<button class=\"btn btn-mini btn-danger\" type=\"button\">\r\n");
      out.write("										<span class=\"icon-remove\"></span>\r\n");
      out.write("									</button>\r\n");
      out.write("								</div></td>\r\n");
      out.write("							<td>$348.42</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"6\" class=\"alignR\">Total products:</td>\r\n");
      out.write("							<td>$448.42</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"6\" class=\"alignR\">Total products:</td>\r\n");
      out.write("							<td>$448.42</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"6\" class=\"alignR\">Total products:</td>\r\n");
      out.write("							<td>$448.42</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td colspan=\"6\" class=\"alignR\">Total products:</td>\r\n");
      out.write("							<td class=\"label label-primary\">$448.42</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("				<br />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<table class=\"table table-bordered\">\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<form class=\"form-inline\">\r\n");
      out.write("									<label style=\"min-width: 159px\"> VOUCHERS Code: </label> <input\r\n");
      out.write("										type=\"text\" class=\"input-medium\" placeholder=\"CODE\">\r\n");
      out.write("									<button type=\"submit\" class=\"shopBtn\">ADD</button>\r\n");
      out.write("								</form>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("				<table class=\"table table-bordered\">\r\n");
      out.write("					<tbody>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>ESTIMATE YOUR SHIPPING & TAXES</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>\r\n");
      out.write("								<form class=\"form-horizontal\">\r\n");
      out.write("									<div class=\"control-group\">\r\n");
      out.write("										<label class=\"span2 control-label\" for=\"inputEmail\">Country</label>\r\n");
      out.write("										<div class=\"controls\">\r\n");
      out.write("											<input type=\"text\" placeholder=\"Country\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"control-group\">\r\n");
      out.write("										<label class=\"span2 control-label\" for=\"inputPassword\">Post\r\n");
      out.write("											Code/ Zipcode</label>\r\n");
      out.write("										<div class=\"controls\">\r\n");
      out.write("											<input type=\"password\" placeholder=\"Password\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"control-group\">\r\n");
      out.write("										<div class=\"controls\">\r\n");
      out.write("											<button type=\"submit\" class=\"shopBtn\">Click to check\r\n");
      out.write("												the price</button>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</form>\r\n");
      out.write("							</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</tbody>\r\n");
      out.write("				</table>\r\n");
      out.write("				<a href=\"products.html\" class=\"shopBtn btn-large\"><span\r\n");
      out.write("					class=\"icon-arrow-left\"></span> Continue Shopping </a> <a\r\n");
      out.write("					href=\"login.html\" class=\"shopBtn btn-large pull-right\">Next <span\r\n");
      out.write("					class=\"icon-arrow-right\"></span></a>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
